Changes needed for compiling with SSL and dynamic runtime linking
agoragames/curl pull request #1
Opened 2017-10-27 13:25 UTC by robotfoot

#### Summary of added/changed functionality:

This PR contains several changes needed to successfully compile the SDK with both dynamic linking and SSL enabled.

#### Links to other repositories if this work will encompass changes to other components such as the dashboard site, SDK, etc.:

TBD

#### Assigned reviewers:
- [ ] @mvdavid7 
- [ ] @blafountain 

#### Link(s) to relevant issues:

https://wbagora.atlassian.net/browse/WD-720

2017-10-30 14:45 UTC, mvdavid7 requested changes

2017-10-30 14:45 UTC, mvdavid7 commented on CMakeLists.txt
> +if(CMAKE_USE_OPENSSL)
I would add a comment here on why we did this.

2017-10-31 15:32 UTC, mvdavid7 approved these changes

2017-10-31 15:36 UTC, nyx commented
This is a super complex intersection of bits, however after in person discussions with @mvdavid7 I think this makes sense. 👍

2017-10-31 15:37 UTC, mvdavid7 commented
@blafountain approved IRL

2017-10-31 15:37 UTC, merged